# Generated by Django 5.2.3 on 2025-06-26 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('task_des', models.TextField()),
                ('is_complete', models.BooleanField(default=False)),
                ('task_ass_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
